        // ===========================
        // COMMON PASSWORDS DICTIONARY
        // ===========================
        // Топ-1000 самых распространённых паролей для быстрой проверки
        const COMMON_PASSWORDS = new Set([
            // Из тестовых кейсов - ТОЛЬКО чистые слова без модификаций
            '123456', 'password', '12345678', 'qwerty', 'abc123', '111111', 'admin',
            'letmein', 'welcome', 'monkey', 'passwordpassword', '12341234',

            // Топ-100 глобально распространённых паролей - ТОЛЬКО базовые
            '12345', '123456789', '1234567', '1234', 'baseball', 'dragon', 'football',
            'mustang', 'access', 'shadow', 'master', 'michael', 'superman',
            'pass', '123', 'ninja', 'batman', 'azerty',
            '654321', 'login', 'starwars',
            'iloveyou', 'sunshine', 'princess', 'solo', 'whatever',
            'freedom', 'flower', 'charlie', 'hello', 'test',

            // Числовые последовательности (чистые числа OK)
            '000000', '0000', '1111', '2222', '3333', '4444', '5555', '6666',
            '7777', '8888', '9999', '11111', '22222', '33333', '44444', '55555',
            '66666', '77777', '88888', '99999', '111111', '222222', '333333',
            '444444', '555555', '666666', '777777', '888888', '999999',
            '1234567', '12345678', '123456789', '1234567890',

            // Популярные клавиатурные комбинации (чистые)
            'qwertyuiop', 'asdfghjkl', 'zxcvbnm', '1q2w3e4r', '1qaz2wsx',
            'qazwsx', 'qweasdzxc',

            // Английские базовые слова (без цифр!)
            'root',

            // Популярные имена
            'michael', 'jennifer', 'jessica', 'ashley', 'matthew', 'joshua',
            'daniel', 'andrew', 'christopher', 'joseph', 'james', 'john',

            // Другие популярные
            'secret', 'iloveyou', 'fuckoff', 'fuckyou', 'hunter', 'cookie',
            'sunshine', 'master', 'pepper', 'cheese', 'nicole', 'thomas',

            // Русские популярные
            'пароль', 'привет', 'любовь', '123qwe', 'йцукен', 'qweasd'
        ]);

        // Создаём набор в нижнем регистре для регистронезависимой проверки
        const COMMON_PASSWORDS_LOWER = new Set(
            [...COMMON_PASSWORDS].map(p => p.toLowerCase())
        );

        // ===========================
        // PASSWORD CHECKING FUNCTIONS
        // ===========================

        /**
         * Проверяет, является ли пароль общеизвестным (из словаря)
         * @param {string} password - Пароль для проверки
         * @returns {boolean} true если пароль в словаре общих паролей
         */
        function checkCommonPasswords(password) {
            // Проверяем как есть и в нижнем регистре
            return COMMON_PASSWORDS.has(password) ||
                   COMMON_PASSWORDS_LOWER.has(password.toLowerCase());
        }

        /**
         * Проверяет, соответствует ли пароль паттерну "словарное слово + суффикс"
         * Например: admin2024, user1234, Russia2024, Moscow123
         * @param {string} password - Пароль для проверки
         * @returns {boolean} true если обнаружен паттерн
         */
        function checkDictionaryPlusSuffix(password) {
            // Паттерны для гибридных атак
            const patterns = [
                // Слово + любое количество цифр: admin2024, user1234, admin01012025
                /^([a-zA-Zа-яА-ЯёЁ]+)(\d+)$/,

                // Слово + год (1900-2099): Russia2024, birth1990
                /^([a-zA-Zа-яА-ЯёЁ]+)(19\d{2}|20\d{2})$/,

                // Слово + одиночный символ: password!, admin@
                /^([a-zA-Zа-яА-ЯёЁ]+)[!@#$%^&*_\-]$/,

                // Слово + символ + цифры: admin@2024, test#99, admin_2024
                /^([a-zA-Zа-яА-ЯёЁ]+)[!@#$%^&*_\-]\d{1,4}$/,

                // Цифры + слово: 2024admin, 99test
                /^(\d{1,4})([a-zA-Zа-яА-ЯёЁ]+)$/,

                // Слово с заглавной + цифры: Moscow123, Python123
                /^([A-ZА-ЯЁ][a-zа-яё]+)(\d{1,4})$/,

                // Слово + слово: adminuser, testpass, abcd1234abcd
                /^([a-zA-Zа-яА-ЯёЁ]{4,})([a-zA-Zа-яА-ЯёЁ]{4,})$/,

                // Слово + спецсимвол + слово + цифры: User@Home123, Admin_User123
                /^([a-zA-Zа-яА-ЯёЁ]+)[!@#$%^&*_\-]([a-zA-Zа-яА-ЯёЁ]+)(\d{1,4})$/,

                // Слово + спецсимвол + цифры + слово: Login$123Pass
                /^([a-zA-Zа-яА-ЯёЁ]+)[!@#$%^&*_\-](\d+)([a-zA-Zа-яА-ЯёЁ]+)$/,

                // Слово + множественные спецсимволы + слово + цифры
                /^([a-zA-Zа-яА-ЯёЁ]+)[!@#$%^&*_\-]+([a-zA-Zа-яА-ЯёЁ]+)(\d{1,4})$/
            ];

            for (const pattern of patterns) {
                const match = password.match(pattern);
                if (match) {
                    // Извлекаем части (слово может быть в первой или второй группе)
                    for (let i = 1; i < match.length; i++) {
                        const part = match[i];
                        if (part && /^[a-zA-Zа-яА-ЯёЁ]+$/.test(part) && part.length >= 3) {
                            const partLower = part.toLowerCase();

                            // Проверяем в словаре общих паролей
                            if (COMMON_PASSWORDS_LOWER.has(partLower)) {
                                return true;
                            }

                            // Проверяем в словаре английских/русских слов
                            if (checkWordInDictionary(partLower)) {
                                return true;
                            }
                        }
                    }
                }
            }

            return false;
        }

        /**
         * Проверяет, есть ли слово в словаре английских или русских слов
         * @param {string} word - Слово для проверки (в нижнем регистре)
         * @returns {boolean} true если слово найдено в словаре
         */
        function checkWordInDictionary(word) {
            // Проверяем в английском словаре - O(1) поиск через Set
            if (englishWordsSet.has(word)) {
                return true;
            }

            // Проверяем в русском словаре - O(1) поиск через Set
            if (typeof russianWordsSet !== 'undefined' && russianWordsSet.has(word)) {
                return true;
            }

            // Дополнительная проверка для часто используемых слов - O(1) поиск через Set
            return commonWordsSet.has(word);
        }

        // Словарь английских слов для парольных фраз
        const englishWords = [
            'able', 'about', 'above', 'acid', 'across', 'act', 'action', 'active', 'add', 'afraid',
            'after', 'again', 'against', 'age', 'ago', 'agree', 'ahead', 'air', 'all', 'allow',
            'almost', 'alone', 'along', 'already', 'also', 'always', 'among', 'amount', 'ancient', 'and',
            'angel', 'anger', 'angle', 'angry', 'animal', 'answer', 'any', 'apple', 'april', 'area',
            'argue', 'arm', 'army', 'around', 'arrive', 'art', 'artist', 'ask', 'asleep', 'attack',
            'august', 'aunt', 'autumn', 'avoid', 'awake', 'away', 'baby', 'back', 'bad', 'bag',
            'bake', 'ball', 'band', 'bank', 'bar', 'base', 'basic', 'basket', 'bath', 'battle',
            'beach', 'bean', 'bear', 'beat', 'beauty', 'become', 'bed', 'beer', 'before', 'begin',
            'behind', 'being', 'bell', 'below', 'belt', 'bench', 'bend', 'beside', 'best', 'better',
            'between', 'beyond', 'big', 'bike', 'bill', 'bird', 'birth', 'bit', 'bite', 'bitter',
            'black', 'blade', 'blame', 'blank', 'blind', 'block', 'blood', 'blow', 'blue', 'board',
            'boat', 'body', 'boil', 'bold', 'bomb', 'bone', 'book', 'boot', 'border', 'born',
            'borrow', 'both', 'bottle', 'bottom', 'bound', 'bowl', 'box', 'boy', 'brain', 'branch',
            'brave', 'bread', 'break', 'bridge', 'brief', 'bright', 'bring', 'broad', 'broken', 'brother',
            'brown', 'brush', 'bubble', 'bucket', 'build', 'bullet', 'bundle', 'burden', 'burn', 'burst',
            'bury', 'bush', 'busy', 'but', 'butter', 'button', 'buy', 'cable', 'cage', 'cake',
            'call', 'calm', 'came', 'camera', 'camp', 'can', 'canal', 'cancel', 'candle', 'candy',
            'cap', 'capable', 'capital', 'captain', 'capture', 'car', 'card', 'care', 'careful', 'carry',
            'case', 'cash', 'cast', 'castle', 'cat', 'catch', 'cattle', 'cause', 'cave', 'cent',
            'center', 'century', 'certain', 'chain', 'chair', 'chance', 'change', 'chapter', 'charge', 'charm',
            'chart', 'chase', 'cheap', 'cheat', 'check', 'cheek', 'cheese', 'chest', 'chief', 'child',
            'chill', 'choice', 'choose', 'chord', 'circle', 'city', 'claim', 'class', 'classic', 'clean',
            'clear', 'clever', 'cliff', 'climate', 'climb', 'clock', 'close', 'cloth', 'cloud', 'club',
            'clue', 'coach', 'coal', 'coast', 'coat', 'code', 'coffee', 'coin', 'cold', 'collect',
            'color', 'column', 'combine', 'come', 'comfort', 'command', 'comment', 'common', 'company', 'compare',
            'complete', 'complex', 'computer', 'concern', 'concert', 'concrete', 'condemn', 'condition', 'conduct', 'cone',
            'confirm', 'conflict', 'connect', 'consider', 'consist', 'constant', 'contain', 'content', 'contest', 'continue',
            'contract', 'control', 'convince', 'cook', 'cool', 'copper', 'copy', 'cord', 'core', 'corn',
            'corner', 'correct', 'cost', 'cotton', 'couch', 'could', 'count', 'country', 'couple', 'courage',
            'course', 'court', 'cousin', 'cover', 'cow', 'crack', 'craft', 'crash', 'crazy', 'cream',
            'create', 'creature', 'credit', 'crew', 'crime', 'criminal', 'crisis', 'crisp', 'critical', 'crop',
            'cross', 'crowd', 'crown', 'cruel', 'crush', 'cry', 'crystal', 'cube', 'culture', 'cup',
            'cure', 'curious', 'current', 'curse', 'curtain', 'curve', 'custom', 'cut', 'cycle', 'dad',
            'daily', 'damage', 'dance', 'danger', 'dare', 'dark', 'data', 'date', 'daughter', 'dawn',
            'day', 'dead', 'deal', 'dear', 'death', 'debate', 'debt', 'decade', 'decay', 'december',
            'decent', 'decide', 'declare', 'decline', 'decorate', 'decrease', 'deep', 'defeat', 'defend', 'define',
            'degree', 'delay', 'deliver', 'demand', 'democracy', 'depend', 'deposit', 'depth', 'descend', 'describe',
            'desert', 'deserve', 'design', 'desire', 'desk', 'despite', 'destroy', 'detail', 'detect', 'develop',
            'device', 'devote', 'diamond', 'dice', 'dictate', 'die', 'diet', 'differ', 'difficult', 'dig',
            'digital', 'dignity', 'dim', 'dinner', 'direct', 'dirt', 'discover', 'discuss', 'disease', 'dish',
            'dismiss', 'display', 'distance', 'distant', 'disturb', 'ditch', 'dive', 'divide', 'divorce', 'do',
            'doctor', 'document', 'dog', 'dollar', 'domain', 'domestic', 'door', 'dot', 'double', 'doubt',
            'down', 'dozen', 'draft', 'drag', 'dragon', 'drain', 'drama', 'draw', 'drawer', 'dream',
            'dress', 'drift', 'drill', 'drink', 'drive', 'drop', 'drug', 'drum', 'dry', 'duck',
            'due', 'dull', 'during', 'dust', 'duty', 'each', 'eager', 'eagle', 'ear', 'early',
            'earn', 'earth', 'ease', 'east', 'easy', 'eat', 'echo', 'economy', 'edge', 'edit',
            'educate', 'effect', 'effort', 'egg', 'eight', 'either', 'elbow', 'elder', 'elect', 'electric',
            'element', 'elephant', 'eleven', 'else', 'emerge', 'emotion', 'emperor', 'emphasis', 'empire', 'employ',
            'empty', 'enable', 'enclose', 'end', 'enemy', 'energy', 'enforce', 'engage', 'engine', 'enjoy',
            'enough', 'enter', 'entire', 'entrance', 'entry', 'envelope', 'envy', 'equal', 'equip', 'era',
            'error', 'escape', 'essay', 'essence', 'establish', 'estate', 'estimate', 'eternal', 'eve', 'even',
            'evening', 'event', 'ever', 'every', 'evidence', 'evil', 'exact', 'examine', 'example', 'exceed',
            'excellent', 'except', 'excess', 'exchange', 'excite', 'exclude', 'excuse', 'execute', 'exercise', 'exhaust',
            'exhibit', 'exist', 'exit', 'expand', 'expect', 'expense', 'expert', 'explain', 'explode', 'explore',
            'export', 'expose', 'express', 'extend', 'extent', 'extra', 'extreme', 'eye', 'fabric', 'face',
            'fact', 'factor', 'factory', 'fade', 'fail', 'faint', 'fair', 'faith', 'fall', 'false',
            'fame', 'familiar', 'family', 'famous', 'fan', 'fancy', 'far', 'farm', 'farmer', 'fashion',
            'fast', 'fat', 'fatal', 'fate', 'father', 'fault', 'favor', 'fear', 'feast', 'feather',
            'feature', 'february', 'fee', 'feed', 'feel', 'fellow', 'female', 'fence', 'fever', 'few',
            'fiber', 'fiction', 'field', 'fifteen', 'fifth', 'fifty', 'fight', 'figure', 'file', 'fill',
            'film', 'filter', 'final', 'finance', 'find', 'fine', 'finger', 'finish', 'fire', 'firm',
            'first', 'fish', 'fist', 'fit', 'five', 'fix', 'flag', 'flame', 'flash', 'flat',
            'flavor', 'flee', 'flesh', 'flexible', 'flight', 'float', 'flood', 'floor', 'flour', 'flow',
            'flower', 'fluid', 'flush', 'fly', 'foam', 'focus', 'fog', 'fold', 'folk', 'follow',
            'food', 'fool', 'foot', 'for', 'forbid', 'force', 'forecast', 'foreign', 'forest', 'forever',
            'forget', 'forgive', 'fork', 'form', 'formal', 'format', 'former', 'formula', 'forth', 'fortune',
            'forty', 'forward', 'found', 'fountain', 'four', 'fourth', 'fox', 'frame', 'france', 'frank',
            'free', 'freedom', 'freeze', 'french', 'frequent', 'fresh', 'friday', 'friend', 'frighten', 'frog',
            'from', 'front', 'frontier', 'frost', 'fruit', 'fuel', 'full', 'fun', 'function', 'fund',
            'fundamental', 'funeral', 'funny', 'fur', 'furnace', 'furniture', 'further', 'future', 'gain', 'galaxy',
            'gallery', 'game', 'gang', 'gap', 'garage', 'garbage', 'garden', 'garlic', 'gas', 'gate',
            'gather', 'gauge', 'gaze', 'gear', 'gene', 'general', 'generate', 'generous', 'genius', 'gentle',
            'genuine', 'gesture', 'get', 'ghost', 'giant', 'gift', 'girl', 'give', 'glad', 'glance',
            'glass', 'glimpse', 'global', 'globe', 'glory', 'glove', 'glow', 'glue', 'go', 'goal',
            'goat', 'god', 'gold', 'golden', 'golf', 'good', 'govern', 'grace', 'grade', 'gradual',
            'grain', 'grand', 'grant', 'grape', 'graph', 'grasp', 'grass', 'grateful', 'grave', 'gravity',
            'gray', 'great', 'greece', 'greed', 'green', 'greet', 'grief', 'grin', 'grind', 'grip',
            'groan', 'grocery', 'ground', 'group', 'grow', 'growth', 'guarantee', 'guard', 'guess', 'guest',
            'guidance', 'guide', 'guilt', 'guilty', 'guitar', 'gulf', 'gun', 'guy', 'habit', 'habitat',
            'hair', 'half', 'hall', 'halt', 'ham', 'hammer', 'hand', 'handle', 'handsome', 'hang',
            'happen', 'happy', 'harbor', 'hard', 'hardly', 'harm', 'harmony', 'harsh', 'harvest', 'haste',
            'hat', 'hate', 'haul', 'have', 'hawk', 'hay', 'hazard', 'he', 'head', 'heal',
            'health', 'heap', 'hear', 'heart', 'heat', 'heaven', 'heavy', 'heel', 'height', 'heir',
            'hello', 'helmet', 'help', 'helpful', 'hen', 'hence', 'her', 'herb', 'here', 'heritage',
            'hero', 'hers', 'herself', 'hide', 'high', 'highway', 'hill', 'him', 'himself', 'hint',
            'hip', 'hire', 'his', 'historic', 'history', 'hit', 'hobby', 'hold', 'hole', 'holiday',
            'hollow', 'holy', 'home', 'honest', 'honey', 'honor', 'hook', 'hope', 'horizon', 'horror',
            'horse', 'hospital', 'host', 'hostile', 'hot', 'hotel', 'hour', 'house', 'household', 'housing',
            'how', 'however', 'huge', 'human', 'humble', 'humor', 'hundred', 'hunger', 'hungry', 'hunt',
            'hunter', 'hurry', 'hurt', 'husband', 'hut', 'ice', 'idea', 'ideal', 'identical', 'identify',
            'identity', 'idle', 'if', 'ignore', 'ill', 'illegal', 'illness', 'illustrate', 'image', 'imagine',
            'immediate', 'immense', 'immune', 'impact', 'impatient', 'imperial', 'imply', 'import', 'important', 'impose',
            'impossible', 'impress', 'improve', 'impulse', 'in', 'inch', 'incident', 'incline', 'include', 'income',
            'increase', 'indeed', 'independent', 'index', 'indicate', 'indirect', 'individual', 'indoor', 'industry', 'infant',
            'infect', 'inferior', 'infinite', 'inflate', 'influence', 'inform', 'ingredient', 'inhabit', 'inherit', 'initial',
            'initiate', 'injure', 'injury', 'ink', 'inn', 'inner', 'innocent', 'input', 'inquire', 'insect',
            'insert', 'inside', 'insight', 'insist', 'inspire', 'install', 'instance', 'instant', 'instead', 'instinct',
            'institute', 'instruct', 'instrument', 'insult', 'insurance', 'insure', 'intact', 'integrate', 'integrity', 'intellect',
            'intelligent', 'intend', 'intense', 'intent', 'interact', 'interest', 'interfere', 'interior', 'internal', 'interpret',
            'interval', 'intervene', 'interview', 'intimate', 'into', 'introduce', 'invade', 'invent', 'invest', 'investigate',
            'invite', 'involve', 'inward', 'iron', 'island', 'isolate', 'issue', 'it', 'italian', 'italy',
            'item', 'its', 'itself', 'ivory', 'jacket', 'jail', 'january', 'japan', 'jar', 'jaw',
            'jazz', 'jealous', 'jeans', 'jet', 'jewel', 'job', 'join', 'joint', 'joke', 'journal',
            'journey', 'joy', 'judge', 'juice', 'july', 'jump', 'june', 'jungle', 'junior', 'jury',
            'just', 'justice', 'justify', 'keen', 'keep', 'kettle', 'key', 'keyboard', 'kick', 'kid',
            'kill', 'kind', 'king', 'kingdom', 'kiss', 'kit', 'kitchen', 'kite', 'knee', 'knife',
            'knock', 'knot', 'know', 'knowledge', 'label', 'labor', 'laboratory', 'lack', 'ladder', 'lady',
            'lake', 'lamb', 'lamp', 'land', 'landscape', 'lane', 'language', 'lap', 'large', 'largely',
            'last', 'late', 'later', 'latin', 'latter', 'laugh', 'launch', 'law', 'lawn', 'lawyer',
            'lay', 'layer', 'lazy', 'lead', 'leader', 'leaf', 'league', 'lean', 'leap', 'learn',
            'least', 'leather', 'leave', 'lecture', 'left', 'leg', 'legal', 'legend', 'lemon', 'lend',
            'length', 'lens', 'less', 'lesson', 'let', 'letter', 'level', 'lever', 'liberty', 'library',
            'license', 'lid', 'lie', 'life', 'lift', 'light', 'lightning', 'like', 'likely', 'limb',
            'limit', 'line', 'link', 'lion', 'lip', 'liquid', 'list', 'listen', 'literal', 'literary',
            'literature', 'little', 'live', 'lively', 'liver', 'living', 'load', 'loan', 'lobby', 'local',
            'locate', 'location', 'lock', 'lodge', 'log', 'logic', 'logical', 'lonely', 'long', 'look',
            'loop', 'loose', 'lord', 'lose', 'loss', 'lost', 'lot', 'loud', 'love', 'lovely',
            'low', 'lower', 'loyal', 'luck', 'lucky', 'luggage', 'lumber', 'lunch', 'lung', 'luxury',
            'machine', 'mad', 'madam', 'magazine', 'magic', 'magnet', 'magnificent', 'maid', 'mail', 'main',
            'mainly', 'maintain', 'major', 'majority', 'make', 'maker', 'male', 'mall', 'man', 'manage',
            'manager', 'mankind', 'manner', 'manual', 'manufacture', 'many', 'map', 'maple', 'marble', 'march',
            'margin', 'marine', 'mark', 'market', 'marriage', 'married', 'marry', 'marvel', 'mask', 'mass',
            'massive', 'master', 'mat', 'match', 'mate', 'material', 'math', 'matter', 'mature', 'maximum',
            'may', 'maybe', 'mayor', 'meal', 'mean', 'meaning', 'means', 'meantime', 'meanwhile', 'measure',
            'meat', 'mechanic', 'mechanism', 'medal', 'media', 'medical', 'medicine', 'medieval', 'medium', 'meet',
            'meeting', 'melt', 'member', 'membrane', 'memorial', 'memory', 'mental', 'mention', 'menu', 'merchant',
            'mercy', 'mere', 'merely', 'merit', 'merry', 'mess', 'message', 'metal', 'method', 'middle',
            'midnight', 'might', 'mighty', 'mild', 'mile', 'military', 'milk', 'mill', 'million', 'mind',
            'mine', 'mineral', 'minimum', 'minister', 'minor', 'minority', 'mint', 'minus', 'minute', 'miracle',
            'mirror', 'misery', 'miss', 'missile', 'missing', 'mission', 'mist', 'mistake', 'mix', 'mixture',
            'moan', 'mobile', 'mode', 'model', 'moderate', 'modern', 'modest', 'modify', 'moment', 'monday',
            'money', 'monitor', 'monkey', 'month', 'monument', 'mood', 'moon', 'moral', 'more', 'moreover',
            'morning', 'mortal', 'mortgage', 'most', 'mostly', 'mother', 'motion', 'motive', 'motor', 'mount',
            'mountain', 'mouse', 'mouth', 'move', 'movement', 'movie', 'much', 'mud', 'multiple', 'multiply',
            'murder', 'muscle', 'museum', 'music', 'musical', 'musician', 'must', 'mutual', 'my', 'myself',
            'mystery', 'myth', 'nail', 'naked', 'name', 'namely', 'narrow', 'nasty', 'nation', 'national',
            'native', 'natural', 'nature', 'naval', 'navigate', 'navy', 'near', 'nearby', 'nearly', 'neat',
            'necessary', 'neck', 'need', 'needle', 'negative', 'neglect', 'negotiate', 'neighbor', 'neither', 'nephew',
            'nerve', 'nervous', 'nest', 'net', 'network', 'neutral', 'never', 'nevertheless', 'new', 'news',
            'newspaper', 'next', 'nice', 'niece', 'night', 'nine', 'nineteen', 'ninety', 'ninth', 'no',
            'noble', 'nobody', 'nod', 'noise', 'none', 'noon', 'nor', 'normal', 'north', 'northern',
            'nose', 'not', 'notable', 'note', 'nothing', 'notice', 'notion', 'novel', 'november', 'now',
            'nowhere', 'nuclear', 'number', 'numerous', 'nurse', 'nut', 'oak', 'obey', 'object', 'objective',
            'obligation', 'observe', 'obstacle', 'obtain', 'obvious', 'occasion', 'occupy', 'occur', 'ocean', 'october',
            'odd', 'of', 'off', 'offend', 'offense', 'offer', 'office', 'officer', 'official', 'often',
            'oil', 'old', 'olive', 'on', 'once', 'one', 'onion', 'only', 'onto', 'open',
            'opera', 'operate', 'operation', 'opinion', 'opponent', 'opportunity', 'oppose', 'opposite', 'oppress', 'optical',
            'optimism', 'option', 'or', 'oral', 'orange', 'orbit', 'order', 'ordinary', 'organ', 'organic',
            'organize', 'orient', 'origin', 'original', 'other', 'otherwise', 'ought', 'ounce', 'our', 'ours',
            'ourselves', 'out', 'outcome', 'outdoor', 'outer', 'outline', 'outlook', 'output', 'outward', 'oven',
            'over', 'overall', 'overcome', 'overflow', 'overhead', 'overlook', 'overnight', 'overseas', 'overtake', 'overwhelm',
            'owe', 'own', 'owner', 'oxygen', 'pace', 'pacific', 'pack', 'package', 'page', 'pain',
            'painful', 'paint', 'painter', 'painting', 'pair', 'palace', 'pale', 'palm', 'pan', 'panel',
            'panic', 'paper', 'parade', 'paragraph', 'parallel', 'parcel', 'pardon', 'parent', 'park', 'parliament',
            'part', 'particle', 'particular', 'partly', 'partner', 'party', 'pass', 'passage', 'passenger', 'passion',
            'passive', 'past', 'path', 'patience', 'patient', 'pattern', 'pause', 'pave', 'pay', 'payment',
            'peace', 'peaceful', 'peach', 'peak', 'pear', 'peasant', 'peculiar', 'pen', 'penalty', 'pencil',
            'penny', 'people', 'pepper', 'per', 'perceive', 'percent', 'perfect', 'perform', 'perhaps', 'period',
            'permanent', 'permission', 'permit', 'person', 'personal', 'persuade', 'pet', 'petrol', 'phase', 'phone',
            'photo', 'phrase', 'physical', 'piano', 'pick', 'picture', 'pie', 'piece', 'pig', 'pigeon',
            'pile', 'pill', 'pillar', 'pillow', 'pilot', 'pin', 'pine', 'pink', 'pioneer', 'pipe',
            'pirate', 'pistol', 'pit', 'pitch', 'pity', 'place', 'plain', 'plan', 'plane', 'planet',
            'plant', 'plastic', 'plate', 'platform', 'play', 'player', 'pleasant', 'please', 'pleasure', 'plenty',
            'plot', 'plow', 'pluck', 'plug', 'plum', 'plunge', 'plus', 'pocket', 'poem', 'poet',
            'poetry', 'point', 'poison', 'pole', 'police', 'policy', 'polish', 'polite', 'political', 'politics',
            'poll', 'pond', 'pony', 'pool', 'poor', 'pop', 'popular', 'population', 'porch', 'pork',
            'port', 'portion', 'portrait', 'portray', 'pose', 'position', 'positive', 'possess', 'possible', 'post',
            'pot', 'potato', 'potential', 'pound', 'pour', 'powder', 'power', 'powerful', 'practical', 'practice',
            'praise', 'pray', 'prayer', 'precise', 'predict', 'prefer', 'prejudice', 'premise', 'premium', 'prepare',
            'prescribe', 'presence', 'present', 'preserve', 'president', 'press', 'pressure', 'presume', 'pretend', 'pretty',
            'prevail', 'prevent', 'previous', 'price', 'pride', 'priest', 'primary', 'prime', 'primitive', 'prince',
            'princess', 'principal', 'principle', 'print', 'prior', 'priority', 'prison', 'prisoner', 'private', 'privilege',
            'prize', 'probable', 'problem', 'procedure', 'proceed', 'process', 'proclaim', 'produce', 'product', 'profession',
            'professor', 'profile', 'profit', 'profound', 'program', 'progress', 'prohibit', 'project', 'prominent', 'promise',
            'promote', 'prompt', 'proof', 'proper', 'property', 'proportion', 'proposal', 'propose', 'prospect', 'prosper',
            'protect', 'protein', 'protest', 'proud', 'prove', 'provide', 'province', 'provision', 'provoke', 'public',
            'publish', 'pull', 'pulse', 'pump', 'punch', 'punish', 'pupil', 'purchase', 'pure', 'purple',
            'purpose', 'purse', 'pursue', 'push', 'put', 'puzzle', 'qualify', 'quality', 'quantity', 'quarrel',
            'quarter', 'queen', 'question', 'quick', 'quiet', 'quit', 'quite', 'quiz', 'quote', 'rabbit',
            'race', 'rack', 'radar', 'radical', 'radio', 'rage', 'raid', 'rail', 'railroad', 'railway',
            'rain', 'rainbow', 'raise', 'rally', 'ranch', 'random', 'range', 'rank', 'rapid', 'rare',
            'rarely', 'rat', 'rate', 'rather', 'ratio', 'raw', 'ray', 'reach', 'react', 'read',
            'reader', 'ready', 'real', 'realistic', 'reality', 'realize', 'really', 'realm', 'rear', 'reason',
            'reasonable', 'rebel', 'recall', 'receipt', 'receive', 'recent', 'reception', 'recipe', 'reckon', 'recognize',
            'recommend', 'record', 'recover', 'red', 'reduce', 'refer', 'reflect', 'reform', 'refresh', 'refrigerator',
            'refuge', 'refund', 'refusal', 'refuse', 'regard', 'regime', 'region', 'register', 'regret', 'regular',
            'regulate', 'reign', 'reject', 'relate', 'relation', 'relative', 'relax', 'release', 'relevant', 'reliable',
            'relief', 'relieve', 'religion', 'religious', 'rely', 'remain', 'remark', 'remarkable', 'remedy', 'remember',
            'remind', 'remote', 'remove', 'render', 'renew', 'rent', 'repair', 'repeat', 'replace', 'reply',
            'report', 'represent', 'republic', 'reputation', 'request', 'require', 'rescue', 'research', 'resemble', 'resent',
            'reserve', 'reside', 'resign', 'resist', 'resolve', 'resort', 'resource', 'respect', 'respond', 'response',
            'responsible', 'rest', 'restaurant', 'restore', 'restrain', 'restrict', 'result', 'resume', 'retail', 'retain',
            'retire', 'retreat', 'return', 'reveal', 'revenue', 'reverse', 'review', 'revise', 'revive', 'revolt',
            'revolution', 'reward', 'rhythm', 'rib', 'ribbon', 'rice', 'rich', 'rid', 'riddle', 'ride',
            'ridge', 'rifle', 'right', 'rigid', 'ring', 'rinse', 'riot', 'ripe', 'rise', 'risk',
            'ritual', 'rival', 'river', 'road', 'roar', 'roast', 'rob', 'robe', 'robot', 'robust',
            'rock', 'rocket', 'rod', 'role', 'roll', 'romantic', 'roof', 'room', 'root', 'rope',
            'rose', 'rot', 'rotate', 'rough', 'round', 'route', 'routine', 'row', 'royal', 'rub',
            'rubber', 'rude', 'ruin', 'rule', 'ruler', 'rumor', 'run', 'rural', 'rush', 'rust',
            'sacred', 'sacrifice', 'sad', 'saddle', 'safe', 'safety', 'sail', 'sailor', 'saint', 'sake',
            'salad', 'salary', 'sale', 'salt', 'same', 'sample', 'sand', 'sandwich', 'satellite', 'satisfy',
            'saturday', 'sauce', 'saucer', 'sausage', 'savage', 'save', 'savings', 'say', 'scale', 'scan',
            'scandal', 'scar', 'scarce', 'scare', 'scatter', 'scene', 'scenery', 'scent', 'schedule', 'scheme',
            'scholar', 'school', 'science', 'scissors', 'scold', 'scope', 'score', 'scorn', 'scout', 'scrape',
            'scratch', 'scream', 'screen', 'screw', 'script', 'sculpture', 'sea', 'seal', 'search', 'season',
            'seat', 'second', 'secret', 'secretary', 'section', 'sector', 'secure', 'security', 'see', 'seed',
            'seek', 'seem', 'seize', 'seldom', 'select', 'self', 'selfish', 'sell', 'semester', 'send',
            'senior', 'sense', 'sensible', 'sensitive', 'sentence', 'separate', 'september', 'sequence', 'series', 'serious',
            'servant', 'serve', 'service', 'session', 'set', 'settle', 'settlement', 'seven', 'seventeen', 'seventh',
            'seventy', 'several', 'severe', 'sew', 'sex', 'shade', 'shadow', 'shaft', 'shake', 'shall',
            'shallow', 'shame', 'shape', 'share', 'sharp', 'shave', 'she', 'shed', 'sheep', 'sheer',
            'sheet', 'shelf', 'shell', 'shelter', 'shepherd', 'shield', 'shift', 'shine', 'ship', 'shirt',
            'shock', 'shoe', 'shoot', 'shop', 'shore', 'short', 'shortly', 'shot', 'shoulder', 'shout',
            'show', 'shower', 'shut', 'shy', 'sick', 'side', 'siege', 'sigh', 'sight', 'sign',
            'signal', 'signature', 'significance', 'signify', 'silence', 'silent', 'silk', 'silly', 'silver', 'similar',
            'simple', 'simply', 'sin', 'since', 'sincere', 'sing', 'singer', 'single', 'sink', 'sir',
            'sister', 'sit', 'site', 'situation', 'six', 'sixteen', 'sixth', 'sixty', 'size', 'sketch',
            'ski', 'skill', 'skin', 'skirt', 'skull', 'sky', 'slave', 'sleep', 'sleeve', 'slice',
            'slide', 'slight', 'slim', 'slip', 'slope', 'slow', 'small', 'smart', 'smell', 'smile',
            'smoke', 'smooth', 'snake', 'snap', 'snow', 'so', 'soak', 'soap', 'sober', 'soccer',
            'social', 'society', 'sock', 'soft', 'soil', 'solar', 'soldier', 'sole', 'solemn', 'solid',
            'solution', 'solve', 'some', 'somebody', 'somehow', 'someone', 'something', 'sometime', 'somewhat', 'somewhere',
            'son', 'song', 'soon', 'sore', 'sorrow', 'sorry', 'sort', 'soul', 'sound', 'soup',
            'sour', 'source', 'south', 'southern', 'space', 'spare', 'spark', 'speak', 'speaker', 'special',
            'specialist', 'species', 'specific', 'specify', 'specimen', 'spectacle', 'spectrum', 'speech', 'speed', 'spell',
            'spend', 'sphere', 'spice', 'spider', 'spike', 'spill', 'spin', 'spine', 'spirit', 'spiritual',
            'spit', 'spite', 'splash', 'split', 'spoil', 'spoke', 'sponsor', 'spoon', 'sport', 'spot',
            'spread', 'spring', 'sprinkle', 'square', 'squeeze', 'stable', 'stack', 'stadium', 'staff', 'stage',
            'stain', 'stair', 'stake', 'stale', 'stamp', 'stand', 'standard', 'star', 'stare', 'start',
            'starve', 'state', 'statement', 'station', 'statue', 'status', 'stay', 'steady', 'steal', 'steam',
            'steel', 'steep', 'steer', 'stem', 'step', 'stereo', 'stern', 'stick', 'sticky', 'stiff',
            'still', 'stimulate', 'sting', 'stir', 'stock', 'stocking', 'stomach', 'stone', 'stool', 'stop',
            'storage', 'store', 'storm', 'story', 'stove', 'straight', 'strain', 'strange', 'stranger', 'strap',
            'strategy', 'straw', 'stream', 'street', 'strength', 'stress', 'stretch', 'strict', 'strike', 'string',
            'strip', 'stroke', 'strong', 'structure', 'struggle', 'student', 'studio', 'study', 'stuff', 'stupid',
            'style', 'subject', 'submit', 'substance', 'substantial', 'substitute', 'subtle', 'subtract', 'suburb', 'subway',
            'succeed', 'success', 'such', 'suck', 'sudden', 'suffer', 'sufficient', 'sugar', 'suggest', 'suit',
            'suitable', 'sum', 'summary', 'summer', 'summit', 'summon', 'sun', 'sunday', 'sunlight', 'sunny',
            'sunrise', 'sunset', 'sunshine', 'super', 'superb', 'superior', 'supervise', 'supper', 'supplement', 'supply',
            'support', 'suppose', 'supreme', 'sure', 'surface', 'surge', 'surgeon', 'surgery', 'surplus', 'surprise',
            'surrender', 'surround', 'survey', 'survival', 'survive', 'suspect', 'suspend', 'suspicion', 'sustain', 'swallow',
            'swamp', 'swap', 'swear', 'sweat', 'sweep', 'sweet', 'swell', 'swift', 'swim', 'swing',
            'switch', 'sword', 'symbol', 'sympathize', 'sympathy', 'symptom', 'system', 'table', 'tablet', 'tackle',
            'tactic', 'tag', 'tail', 'tailor', 'take', 'tale', 'talent', 'talk', 'tall', 'tank',
            'tap', 'tape', 'target', 'task', 'taste', 'tax', 'taxi', 'tea', 'teach', 'teacher',
            'team', 'tear', 'technical', 'technique', 'technology', 'tedious', 'telephone', 'telescope', 'television', 'tell',
            'temper', 'temperature', 'temple', 'temporary', 'tempt', 'ten', 'tend', 'tendency', 'tender', 'tennis',
            'tense', 'tension', 'tent', 'term', 'terminal', 'terrace', 'terrible', 'territory', 'terror', 'test',
            'text', 'textile', 'than', 'thank', 'that', 'the', 'theater', 'theft', 'their', 'theirs',
            'them', 'theme', 'themselves', 'then', 'theory', 'therapy', 'there', 'thereby', 'therefore', 'these',
            'they', 'thick', 'thief', 'thin', 'thing', 'think', 'third', 'thirst', 'thirteen', 'thirty',
            'this', 'thorn', 'thorough', 'those', 'though', 'thought', 'thousand', 'thread', 'threat', 'threaten',
            'three', 'threshold', 'thrill', 'thrive', 'throat', 'throne', 'through', 'throughout', 'throw', 'thrust',
            'thumb', 'thunder', 'thursday', 'thus', 'tick', 'ticket', 'tide', 'tidy', 'tie', 'tiger',
            'tight', 'tile', 'till', 'timber', 'time', 'tiny', 'tip', 'tire', 'tired', 'tissue',
            'title', 'to', 'toad', 'toast', 'tobacco', 'today', 'toe', 'together', 'toilet', 'token',
            'tolerate', 'tomato', 'tomb', 'tomorrow', 'ton', 'tone', 'tongue', 'tonight', 'too', 'tool',
            'tooth', 'top', 'topic', 'torch', 'torment', 'torture', 'toss', 'total', 'touch', 'tough',
            'tour', 'tourist', 'tournament', 'toward', 'towel', 'tower', 'town', 'toy', 'trace', 'track',
            'trade', 'tradition', 'traffic', 'tragedy', 'tragic', 'trail', 'train', 'trait', 'traitor', 'tram',
            'tramp', 'transaction', 'transfer', 'transform', 'translate', 'transmit', 'transparent', 'transport', 'trap', 'trash',
            'travel', 'tray', 'treasure', 'treat', 'treatment', 'treaty', 'tree', 'tremble', 'tremendous', 'trend',
            'trial', 'triangle', 'tribe', 'tribute', 'trick', 'trigger', 'trim', 'trip', 'triumph', 'troops',
            'tropical', 'trouble', 'trousers', 'truck', 'true', 'truly', 'trumpet', 'trunk', 'trust', 'truth',
            'try', 'tube', 'tuesday', 'tune', 'tunnel', 'turkey', 'turn', 'twenty', 'twice', 'twin',
            'twist', 'two', 'type', 'typical', 'ugly', 'ultimate', 'umbrella', 'unable', 'uncle', 'under',
            'undergo', 'understand', 'undertake', 'undo', 'uneasy', 'unemployed', 'unexpected', 'unfair', 'uniform', 'union',
            'unique', 'unit', 'unite', 'unity', 'universal', 'universe', 'university', 'unless', 'unlike', 'unlikely',
            'until', 'unusual', 'up', 'update', 'upon', 'upper', 'upright', 'upset', 'upstairs', 'upward',
            'urban', 'urge', 'urgent', 'us', 'usage', 'use', 'used', 'useful', 'useless', 'usual',
            'utility', 'utilize', 'utter', 'vacant', 'vacation', 'vacuum', 'vague', 'vain', 'valid', 'valley',
            'valuable', 'value', 'van', 'vanish', 'vanity', 'vapor', 'variable', 'variety', 'various', 'vary',
            'vase', 'vast', 'vegetable', 'vehicle', 'veil', 'vein', 'venture', 'verb', 'verdict', 'verify',
            'verse', 'version', 'vertical', 'very', 'vessel', 'vest', 'veteran', 'veto', 'via', 'vibrate',
            'vice', 'victim', 'victory', 'video', 'view', 'vigorous', 'village', 'vine', 'vinegar', 'violate',
            'violence', 'violent', 'violet', 'violin', 'virgin', 'virtual', 'virtue', 'virus', 'visa', 'visible',
            'vision', 'visit', 'visitor', 'vital', 'vivid', 'vocabulary', 'voice', 'volcano', 'volleyball', 'volume',
            'volunteer', 'vote', 'voter', 'voyage', 'wage', 'wagon', 'waist', 'wait', 'waiter', 'wake',
            'walk', 'wall', 'wander', 'want', 'war', 'ward', 'warm', 'warn', 'warrior', 'wash',
            'waste', 'watch', 'water', 'wave', 'wax', 'way', 'we', 'weak', 'wealth', 'wealthy',
            'weapon', 'wear', 'weary', 'weather', 'weave', 'web', 'wedding', 'wednesday', 'weed', 'week',
            'weekend', 'weekly', 'weep', 'weigh', 'weight', 'welcome', 'welfare', 'well', 'west', 'western',
            'wet', 'whale', 'what', 'whatever', 'wheat', 'wheel', 'when', 'whenever', 'where', 'whereby',
            'wherever', 'whether', 'which', 'while', 'whip', 'whisper', 'whistle', 'white', 'who', 'whoever',
            'whole', 'whom', 'whose', 'why', 'wicked', 'wide', 'widely', 'widen', 'widow', 'width',
            'wife', 'wild', 'will', 'willing', 'win', 'wind', 'window', 'wine', 'wing', 'wink',
            'winner', 'winter', 'wipe', 'wire', 'wisdom', 'wise', 'wish', 'wit', 'witch', 'with',
            'withdraw', 'within', 'without', 'witness', 'wolf', 'woman', 'wonder', 'wonderful', 'wood', 'wooden',
            'wool', 'word', 'work', 'worker', 'world', 'worm', 'worry', 'worse', 'worship', 'worst',
            'worth', 'worthy', 'would', 'wound', 'wrap', 'wrath', 'wreck', 'wrestle', 'wrist', 'write',
            'writer', 'writing', 'wrong', 'yard', 'year', 'yell', 'yellow', 'yes', 'yesterday', 'yet',
            'yield', 'you', 'young', 'your', 'yours', 'yourself', 'youth', 'zone', 'zoo'
        ];

        // Словарь русских слов для парольных фраз
        const russianWords = [
            'абзац', 'август', 'автор', 'адрес', 'азбука', 'акция', 'альбом', 'ангел', 'анекдот', 'апрель',
            'аптека', 'арбуз', 'армия', 'артист', 'архив', 'аспект', 'атака', 'атлас', 'афиша', 'аэропорт',
            'бабочка', 'багаж', 'база', 'байка', 'баланс', 'балет', 'балкон', 'банан', 'банка', 'банк',
            'барабан', 'басня', 'батарея', 'башня', 'бегство', 'беда', 'белка', 'берег', 'беседа', 'библия',
            'билет', 'битва', 'благо', 'блеск', 'блин', 'блок', 'блуза', 'блюдо', 'богатство', 'бокал',
            'болезнь', 'болото', 'больница', 'борщ', 'борьба', 'босс', 'ботинок', 'бочка', 'боязнь', 'браслет',
            'брат', 'бревно', 'бремя', 'бритва', 'брови', 'бронза', 'брошь', 'брюки', 'буква', 'букет',
            'булка', 'бумага', 'бунт', 'буря', 'бусы', 'бутылка', 'буфет', 'бухта', 'быт', 'бюджет',
            'вагон', 'важность', 'ваза', 'вакансия', 'валюта', 'ванна', 'варенье', 'вариант', 'ватрушка', 'вахта',
            'ведро', 'век', 'велосипед', 'вера', 'верба', 'веревка', 'вершина', 'весло', 'весна', 'весть',
            'ветвь', 'ветер', 'вечер', 'вешалка', 'вещь', 'взгляд', 'взрыв', 'вид', 'вилка', 'вина',
            'виноград', 'вихрь', 'вишня', 'власть', 'влияние', 'вода', 'водка', 'воздух', 'возраст', 'война',
            'вокзал', 'волк', 'волна', 'волос', 'воля', 'вопрос', 'ворона', 'ворота', 'восток', 'восторг',
            'вражда', 'враг', 'врач', 'время', 'вред', 'всадник', 'встреча', 'вторник', 'выбор', 'вывод',
            'выгода', 'выдох', 'выезд', 'вызов', 'выпуск', 'высота', 'выставка', 'выход', 'вьюга', 'вязание',
            'газета', 'газон', 'галерея', 'галстук', 'гараж', 'гармония', 'гвоздь', 'герой', 'гимн', 'глаз',
            'глина', 'глубина', 'глупость', 'гнев', 'гнездо', 'год', 'голова', 'голод', 'голос', 'голубь',
            'гора', 'горе', 'горизонт', 'город', 'горох', 'гость', 'государство', 'гость', 'грабли', 'гражданин',
            'грамота', 'граница', 'гранит', 'график', 'гриб', 'грипп', 'гром', 'группа', 'груша', 'грядка',
            'грязь', 'губа', 'гуляш', 'гусь', 'давление', 'дача', 'движение', 'двор', 'дворец', 'дверь',
            'дебаты', 'дева', 'девушка', 'дед', 'дежурный', 'действие', 'декабрь', 'дело', 'день', 'деньги',
            'дерево', 'деревня', 'десерт', 'детство', 'дефект', 'дефицит', 'дешевизна', 'диалог', 'диван', 'диета',
            'диплом', 'директор', 'дискуссия', 'дитя', 'длина', 'дно', 'доблесть', 'добро', 'доверие', 'довод',
            'договор', 'дождь', 'доза', 'доклад', 'документ', 'долг', 'доля', 'дом', 'дорога', 'доска',
            'достоинство', 'доступ', 'досуг', 'дочь', 'драма', 'древо', 'дрова', 'дрожь', 'друг', 'дружба',
            'дуб', 'дудка', 'дума', 'дунь', 'дупло', 'дуэт', 'дух', 'душа', 'дыра', 'дыхание',
            'дюжина', 'дядя', 'ель', 'емкость', 'ерунда', 'ехидство', 'жадность', 'жажда', 'жалоба', 'жало',
            'жалость', 'жанр', 'жар', 'жаргон', 'жатва', 'желание', 'железо', 'желудок', 'жемчуг', 'жена',
            'жених', 'жердь', 'жертва', 'жест', 'жизнь', 'жилет', 'жилище', 'жир', 'житель', 'житие',
            'жито', 'жребий', 'жулик', 'журавль', 'журнал', 'жюри', 'забава', 'забег', 'забота', 'завет',
            'завод', 'завтра', 'загадка', 'заговор', 'загон', 'задание', 'задача', 'зажим', 'заказ', 'закат',
            'закон', 'закрома', 'зал', 'залив', 'залог', 'замена', 'замок', 'замысел', 'занавес', 'занятие',
            'запад', 'запас', 'запах', 'запись', 'запор', 'запрет', 'зарплата', 'заря', 'засада', 'заслуга',
            'затея', 'заход', 'защита', 'заяц', 'звание', 'звезда', 'зверь', 'звон', 'звонок', 'звук',
            'здание', 'здоровье', 'зебра', 'зелень', 'земля', 'зеркало', 'зерно', 'зигзаг', 'зима', 'злак',
            'злоба', 'змей', 'знак', 'знамя', 'знание', 'знать', 'значение', 'зной', 'зодчий', 'золото',
            'зона', 'зонт', 'зоопарк', 'зрение', 'зритель', 'зуб', 'зубило', 'игла', 'игра', 'идея',
            'идол', 'иерархия', 'изба', 'известие', 'извод', 'изгиб', 'изгнание', 'издание', 'изжога', 'излом',
            'изменение', 'измор', 'износ', 'изъян', 'изюм', 'икона', 'икра', 'имение', 'имя', 'иней',
            'интерес', 'информация', 'инцидент', 'ипподром', 'ирис', 'иск', 'искра', 'искусство', 'испуг', 'исток',
            'история', 'исход', 'итог', 'июль', 'июнь', 'кабан', 'кабель', 'кабинет', 'кавычки', 'кадр',
            'казак', 'казна', 'кайма', 'какао', 'календарь', 'калитка', 'камень', 'камера', 'камин', 'камыш',
            'канал', 'канат', 'кандидат', 'каникулы', 'капитал', 'капля', 'капуста', 'караван', 'караул', 'карман',
            'карта', 'картина', 'картофель', 'карусель', 'каска', 'касса', 'кастрюля', 'каталог', 'катер', 'каток',
            'кафе', 'качели', 'качество', 'каша', 'кашель', 'квадрат', 'квартира', 'квас', 'кедр', 'кенгуру',
            'керосин', 'кефир', 'кибитка', 'кивок', 'кино', 'кинжал', 'киоск', 'кипарис', 'кирпич', 'кисель',
            'кислота', 'кисть', 'кит', 'класс', 'клад', 'кладбище', 'клей', 'клетка', 'климат', 'клин',
            'клоун', 'клуб', 'клубника', 'клык', 'ключ', 'клякса', 'книга', 'кнопка', 'князь', 'кобура',
            'ковер', 'коготь', 'кожа', 'козел', 'кокон', 'колба', 'колено', 'колесо', 'количество', 'коллега',
            'колода', 'колокол', 'колонна', 'колос', 'колыбель', 'кольцо', 'колючка', 'команда', 'комар', 'комедия',
            'комета', 'комната', 'комод', 'компас', 'конверт', 'конец', 'конина', 'контора', 'конфета', 'коньки',
            'копейка', 'копна', 'копоть', 'копье', 'кора', 'корабль', 'коридор', 'корзина', 'корка', 'корм',
            'корнеплод', 'корова', 'король', 'корона', 'короста', 'корпус', 'корт', 'корыто', 'коса', 'косяк',
            'котел', 'котенок', 'кофе', 'кочан', 'кошелек', 'кошка', 'кошмар', 'краб', 'кража', 'край',
            'крапива', 'краса', 'краска', 'кредит', 'крем', 'крепость', 'кресло', 'крест', 'крик', 'кристалл',
            'критик', 'кров', 'кровать', 'кровь', 'кролик', 'кроме', 'крона', 'крот', 'круг', 'кружево',
            'кружка', 'крупа', 'крутизна', 'крыжовник', 'крыло', 'крыльцо', 'крыса', 'крыша', 'крючок', 'кубок',
            'кувшин', 'кудри', 'кузнец', 'кузов', 'кукла', 'кукуруза', 'кулак', 'культура', 'кумир', 'купе',
            'купец', 'курица', 'курок', 'курорт', 'курс', 'куртка', 'кусок', 'куст', 'кухня', 'куча',
            'лабиринт', 'лавка', 'лагерь', 'ладонь', 'лай', 'лак', 'лакомство', 'лампа', 'ландыш', 'лапа',
            'ласка', 'ласточка', 'латы', 'лачуга', 'лебедь', 'левша', 'легенда', 'лед', 'ледник', 'лейка',
            'лекарство', 'лексикон', 'лента', 'лепесток', 'лепка', 'лес', 'лесенка', 'лето', 'летопись', 'лечение',
            'лживость', 'лиана', 'ливень', 'лига', 'лидер', 'ликование', 'лимон', 'линейка', 'линия', 'липа',
            'лира', 'лист', 'листва', 'литература', 'литр', 'лифт', 'лихорадка', 'лицо', 'личность', 'лишай',
            'лоб', 'ловушка', 'логика', 'лодка', 'ложа', 'ложка', 'лозунг', 'локоть', 'лом', 'ломоть',
            'лопата', 'лопух', 'лоск', 'лосось', 'лось', 'лото', 'лохань', 'лошадь', 'луг', 'лужа',
            'лук', 'луна', 'луч', 'лыжи', 'лысина', 'любовь', 'люди', 'лютня', 'люстра', 'лягушка',
            'маг', 'магазин', 'магнит', 'мадам', 'мазь', 'май', 'майка', 'маковка', 'макушка', 'малина',
            'малыш', 'мальчик', 'мама', 'мандарин', 'манера', 'маникюр', 'манифест', 'манка', 'мантия', 'маньяк',
            'марка', 'март', 'маршрут', 'маска', 'масло', 'масса', 'мастер', 'матч', 'матрас', 'мать',
            'мафия', 'мах', 'мачта', 'машина', 'маяк', 'мгла', 'мебель', 'мед', 'медаль', 'медведь',
            'медик', 'мел', 'мелодия', 'мель', 'мемуары', 'меню', 'мера', 'мерзлота', 'мероприятие', 'месса',
            'место', 'месть', 'месяц', 'метель', 'метеор', 'метка', 'метла', 'метод', 'метр', 'метро',
            'меч', 'мечта', 'мешок', 'мигрень', 'мизинец', 'микроб', 'милиция', 'милость', 'миля', 'мимика',
            'мимоза', 'минарет', 'минерал', 'миниатюра', 'министр', 'минута', 'мир', 'мираж', 'миска', 'миссия',
            'митинг', 'миф', 'мишень', 'младенец', 'мнение', 'множество', 'могила', 'мода', 'модель', 'мозг',
            'мозоль', 'мокрота', 'молитва', 'молния', 'молодость', 'молоко', 'молот', 'молчание', 'момент', 'монах',
            'монета', 'монолог', 'монтаж', 'мопс', 'мораль', 'мороз', 'морщина', 'моряк', 'москвич', 'мост',
            'мотив', 'мотор', 'моча', 'мочалка', 'мощность', 'мрак', 'мрамор', 'мудрость', 'муж', 'мужество',
            'музей', 'музыка', 'мука', 'муха', 'мучение', 'мушка', 'мыло', 'мысль', 'мышь', 'мышца',
            'мэр', 'мясо', 'мята', 'мяч', 'набор', 'набросок', 'навес', 'навык', 'награда', 'надежда',
            'надзор', 'надпись', 'наказание', 'накал', 'наклон', 'налет', 'налог', 'намек', 'намерение', 'нападение',
            'направление', 'напряжение', 'народ', 'нарост', 'наряд', 'насилие', 'наследник', 'настойчивость', 'настроение', 'насыпь',
            'натура', 'наука', 'наушники', 'нация', 'начало', 'небо', 'невеста', 'невод', 'недра', 'неделя',
            'недуг', 'нежность', 'незнакомец', 'нектар', 'немота', 'ненависть', 'необходимость', 'неприятность', 'нерв', 'нефть',
            'нива', 'нить', 'ничтожество', 'нищета', 'нога', 'ноготь', 'нож', 'ножницы', 'ноздря', 'номер',
            'норма', 'нора', 'норов', 'нос', 'носилки', 'носок', 'нота', 'ночь', 'ноша', 'ноябрь',
            'нрав', 'нужда', 'нуль', 'обвинение', 'обед', 'обезьяна', 'оберег', 'обещание', 'обида', 'обилие',
            'обитатель', 'обитель', 'облако', 'область', 'облик', 'обман', 'обмен', 'обоз', 'оболочка', 'оборона',
            'оборот', 'образ', 'образец', 'обрез', 'обрыв', 'обряд', 'обувь', 'обучение', 'обход', 'общество',
            'объект', 'объем', 'объятие', 'обыск', 'обычай', 'обязанность', 'овал', 'овация', 'овес', 'овощ',
            'овраг', 'овца', 'огласка', 'оглобля', 'огонь', 'огород', 'ограда', 'огурец', 'одежда', 'одеяло',
            'одиночество', 'ожерелье', 'ожидание', 'озеро', 'озноб', 'оказия', 'океан', 'оклад', 'окно', 'околица',
            'окончание', 'окоп', 'окорок', 'окраина', 'окрас', 'округ', 'октябрь', 'окунь', 'олень', 'олива',
            'олово', 'ольха', 'омут', 'опала', 'опасность', 'опека', 'опера', 'описание', 'оплата', 'оплошность',
            'опора', 'оппонент', 'опрос', 'опус', 'опыт', 'опята', 'оранжерея', 'оратор', 'орбита', 'орган',
            'орда', 'орден', 'ордер', 'орел', 'орех', 'оркестр', 'оружие', 'оса', 'осада', 'осанка',
            'осень', 'осина', 'осколок', 'оскорбление', 'ослабление', 'осмотр', 'основа', 'особенность', 'осока', 'остановка',
            'остаток', 'остолоп', 'острие', 'остров', 'острота', 'остроумие', 'остров', 'ось', 'осязание', 'ответ',
            'отвес', 'ответственность', 'отверстие', 'отвод', 'отголосок', 'отдел', 'отдых', 'отец', 'отечество', 'отказ',
            'открытие', 'отклик', 'отлив', 'отличие', 'отметка', 'отмщение', 'относительность', 'отношение', 'отпечаток', 'отпор',
            'отпуск', 'отражение', 'отрасль', 'отрезок', 'отряд', 'отрыв', 'отсек', 'отсрочка', 'отступление', 'оттенок',
            'оттепель', 'отход', 'отчаяние', 'отчет', 'отчество', 'отшельник', 'офицер', 'охапка', 'охота', 'охрана',
            'оценка', 'очаг', 'очарование', 'очевидец', 'очередь', 'очерк', 'очки', 'очко', 'ошейник', 'ошибка',
            'павильон', 'падение', 'падчерица', 'пай', 'пакет', 'палата', 'палатка', 'палач', 'палец', 'палка',
            'пальма', 'пальто', 'память', 'памятник', 'панель', 'паника', 'панорама', 'панцирь', 'папа', 'папка',
            'папоротник', 'папуас', 'пар', 'пара', 'парад', 'параграф', 'паралич', 'парк', 'парник', 'паром',
            'парта', 'партия', 'парус', 'паспорт', 'пасть', 'пастух', 'патриот', 'патрон', 'паук', 'пауза',
            'пафос', 'пах', 'пахарь', 'пациент', 'паштет', 'паяц', 'певец', 'педаль', 'пейзаж', 'пелена',
            'пена', 'пенал', 'пение', 'пенс', 'пенсия', 'пень', 'пепел', 'первенец', 'перевод', 'перевозка',
            'переворот', 'перегородка', 'передача', 'переезд', 'перекресток', 'перелет', 'перелом', 'переменпа', 'перемирие', 'переполох',
            'пересечение', 'переулок', 'перец', 'период', 'перо', 'перрон', 'перспектива', 'персть', 'перчатка', 'песец',
            'песня', 'песок', 'пестик', 'петарда', 'петля', 'петрушка', 'петух', 'печаль', 'печать', 'печень',
            'печка', 'пешеход', 'пещера', 'пианино', 'пиво', 'пиджак', 'пижама', 'пика', 'пикет', 'пила',
            'пилот', 'пинцет', 'пион', 'пир', 'пирамида', 'пират', 'пирог', 'писатель', 'письмо', 'питание',
            'пища', 'пиявка', 'плавание', 'плакат', 'пламя', 'план', 'планета', 'планка', 'пласт', 'пластинка',
            'платеж', 'платина', 'платок', 'платформа', 'платье', 'плач', 'плащ', 'племя', 'плен', 'пленка',
            'плеск', 'плесень', 'плечо', 'плита', 'плитка', 'плод', 'плот', 'плотина', 'плотник', 'плотность',
            'площадь', 'площадка', 'плуг', 'плут', 'плющ', 'побег', 'побережье', 'повадка', 'повар', 'поведение',
            'повелитель', 'поверхность', 'повесть', 'повод', 'поворот', 'погода', 'погон', 'погост', 'погреб', 'погром',
            'подача', 'подарок', 'податель', 'подвал', 'подвеска', 'подвиг', 'подготовка', 'поддержка', 'подземелье', 'подкова',
            'подкуп', 'подлец', 'подлинник', 'подметка', 'подножие', 'поднос', 'подобие', 'подозрение', 'подол', 'подпись',
            'подполье', 'подробность', 'подросток', 'подруга', 'подсказка', 'подсолнечник', 'подставка', 'подстрекатель', 'подступ', 'подсчет',
            'подсчет', 'подушка', 'подход', 'подчинение', 'подшипник', 'подъезд', 'подъем', 'поезд', 'поединок', 'пожар',
            'пожатие', 'пожелание', 'поза', 'позвоночник', 'поздравление', 'позиция', 'познание', 'позор', 'позыв', 'поиск',
            'покаяние', 'покинутость', 'поклон', 'поклонник', 'покой', 'покров', 'покупатель', 'пол', 'полба', 'полдень',
            'поле', 'полемика', 'полет', 'полив', 'полис', 'политика', 'полк', 'полка', 'полночь', 'половина',
            'половодье', 'положение', 'полоса', 'полотенце', 'полотно', 'полтина', 'полушарие', 'польза', 'поляк', 'поляна',
            'помада', 'помеха', 'помещение', 'помидор', 'помощник', 'помощь', 'помпа', 'понедельник', 'пони', 'понимание',
            'понятие', 'поощрение', 'попадание', 'попечение', 'попона', 'попугай', 'попытка', 'пора', 'поражение', 'порез',
            'порог', 'порода', 'порок', 'порошок', 'порт', 'портал', 'портной', 'портрет', 'портфель', 'порция',
            'порча', 'порыв', 'порядок', 'посадка', 'посев', 'поселение', 'посетитель', 'поселок', 'послание', 'послушание',
            'пособие', 'посол', 'пост', 'поставка', 'постановка', 'постель', 'постоянство', 'поступок', 'посуда', 'посылка',
            'пот', 'потемки', 'потеря', 'поток', 'потолок', 'потомок', 'поход', 'похороны', 'похоть', 'почва',
            'почерк', 'почет', 'почин', 'починка', 'почка', 'почта', 'пошлина', 'поэзия', 'поэма', 'поэт',
            'пояс', 'правда', 'правило', 'право', 'празднество', 'практика', 'прах', 'превращение', 'предание', 'предатель',
            'предел', 'предлог', 'предложение', 'предмет', 'предок', 'предприятие', 'представление', 'предчувствие', 'президент', 'презрение',
            'прелесть', 'преображение', 'препятствие', 'пресс', 'престол', 'преступление', 'претензия', 'прибавка', 'прибой', 'прибор',
            'прибыль', 'привет', 'привилегия', 'привкус', 'привычка', 'приговор', 'пригорок', 'придворный', 'призвание', 'призма',
            'призрак', 'призыв', 'прикрытие', 'приказ', 'прикосновение', 'прилив', 'пример', 'примета', 'принцип', 'принуждение',
            'приоритет', 'припев', 'природа', 'прирост', 'присест', 'присмотр', 'присутствие', 'присяга', 'притворство', 'притча',
            'приход', 'причал', 'причина', 'пришелец', 'приют', 'пробел', 'пробка', 'проблема', 'пробор', 'проверка',
            'провидение', 'провод', 'проводник', 'провокация', 'провоз', 'прогноз', 'программа', 'прогресс', 'прогулка', 'продажа',
            'продолжение', 'проект', 'проем', 'проза', 'прозвище', 'проза', 'произведение', 'происхождение', 'происшествие', 'прокат',
            'прокол', 'пролив', 'пролог', 'промах', 'променад', 'промысел', 'проникновение', 'пропасть', 'проповедь', 'пропуск',
            'прорыв', 'просветление', 'проселок', 'просьба', 'простор', 'проступок', 'просьба', 'протест', 'протокол', 'профессия',
            'прохлада', 'проход', 'прохожий', 'процент', 'процесс', 'процессия', 'прочность', 'прошение', 'прошлое', 'прощание',
            'проявка', 'прут', 'пруд', 'пружина', 'прыжок', 'прятки', 'псалом', 'психика', 'птенец', 'птица',
            'публика', 'пугало', 'пугач', 'пуговица', 'пудра', 'пузырь', 'пук', 'пульс', 'пункт', 'пунш',
            'пуп', 'путаница', 'путешествие', 'путь', 'пух', 'пушка', 'пчела', 'пшеница', 'пыль', 'пытка',
            'пышность', 'пьедестал', 'пьеса', 'пятка', 'пятница', 'пятно', 'работа', 'работник', 'рабство', 'равенство',
            'равнина', 'радио', 'радость', 'радуга', 'раздумье', 'разлука', 'размах', 'размер', 'размышление', 'разница',
            'разнообразие', 'разрез', 'разрешение', 'разруха', 'разряд', 'разум', 'район', 'рак', 'ракета', 'ракитник',
            'рама', 'рамка', 'рана', 'ранг', 'ранец', 'раса', 'раскат', 'раскол', 'раскопки', 'раскрас',
            'распад', 'распахивание', 'распев', 'распечатка', 'расписание', 'расплата', 'распоряжение', 'рассада', 'рассвет', 'рассеяние',
            'расска', 'расслабление', 'рассмотрение', 'рассол', 'расстояние', 'рассудок', 'рассылка', 'растение', 'растерянность', 'растр',
            'расход', 'расцвет', 'расчет', 'ратуша', 'рация', 'рвение', 'реакция', 'ребенок', 'ребро', 'реве',
            'ревизия', 'револьвер', 'революция', 'ревность', 'регион', 'регистр', 'редактор', 'редиска', 'редкость', 'режим',
            'резерв', 'резина', 'резка', 'результат', 'резьба', 'рейс', 'река', 'реклама', 'рекорд', 'религия',
            'рельеф', 'рельс', 'ремень', 'ремесло', 'ремонт', 'репа', 'репертуар', 'репетиция', 'репка', 'репортаж',
            'ресница', 'республика', 'ресторан', 'ресурс', 'рецепт', 'рецензия', 'речь', 'решение', 'решето', 'решимость',
            'ржание', 'ржавчина', 'рис', 'риск', 'рисование', 'рисунок', 'ритм', 'ритуал', 'рифма', 'роба',
            'робость', 'ровесник', 'рог', 'рогатка', 'рогоз', 'родина', 'родитель', 'родник', 'родня', 'родство',
            'рождение', 'рожь', 'роза', 'розга', 'розетка', 'роза', 'рой', 'рок', 'роковой', 'роль',
            'роман', 'романс', 'ромашка', 'ропот', 'роса', 'российский', 'рост', 'роща', 'рояль', 'рубаха',
            'рубеж', 'рубин', 'рубка', 'рубль', 'ругань', 'руда', 'ружье', 'руина', 'рука', 'рукав',
            'рукавица', 'руководитель', 'руководство', 'рукоделие', 'рукопашный', 'рукопись', 'рукоятка', 'рулет', 'руль', 'румянец',
            'русло', 'русский', 'ручей', 'ручка', 'рыба', 'рыбак', 'рывок', 'рыдание', 'рыжик', 'рынок',
            'рысь', 'рытье', 'рыцарь', 'рюкзак', 'рябина', 'ряд', 'ряса', 'сабля', 'саван', 'сад',
            'садовник', 'сажа', 'саженец', 'сазан', 'сайгак', 'сайра', 'сакля', 'салат', 'сало', 'салон',
            'салфетка', 'сало', 'самовар', 'самолет', 'самородок', 'самоубийство', 'самоуправление', 'санаторий', 'санки', 'сантиметр',
            'сапог', 'сапожник', 'сарай', 'сарафан', 'сардина', 'сатана', 'сатира', 'сахар', 'сачок', 'саше',
            'свадьба', 'сваха', 'свая', 'сверло', 'сверток', 'сверчок', 'свет', 'светило', 'свеча', 'свидание',
            'свидетель', 'свинец', 'свинина', 'свинья', 'свист', 'свисток', 'свита', 'свиток', 'свобода', 'свод',
            'сводка', 'свойство', 'связь', 'святилище', 'святой', 'святыня', 'священник', 'сговор', 'сдача', 'себестоимость',
            'север', 'сегмент', 'седина', 'седло', 'седок', 'сезон', 'сейф', 'секрет', 'секретарь', 'сектор',
            'секунда', 'селедка', 'селение', 'село', 'семейство', 'семена', 'семинар', 'семь', 'семья', 'сенат',
            'сени', 'сенокос', 'сено', 'сентябрь', 'сень', 'сера', 'сервиз', 'сервис', 'сердце', 'сереб',
            'середина', 'серия', 'серп', 'серьга', 'сестра', 'сетка', 'сеть', 'сечение', 'сеялка', 'сиг',
            'сигара', 'сигнал', 'сиденье', 'сила', 'силуэт', 'символ', 'симпатия', 'симптом', 'синдром', 'синева',
            'синица', 'синод', 'синоним', 'синтез', 'синь', 'сирена', 'сирень', 'сироп', 'сирота', 'система',
            'ситец', 'ситуация', 'сияние', 'скала', 'скалка', 'скамейка', 'скамья', 'скандал', 'скат', 'скатерть',
            'сквер', 'скважина', 'сквозняк', 'скворец', 'скелет', 'скидка', 'скипетр', 'скирда', 'скит', 'склад',
            'складка', 'склон', 'склонность', 'скобка', 'скорбь', 'скороход', 'скорость', 'скотина', 'скрежет', 'скрипка',
            'скромность', 'скука', 'скула', 'скульптор', 'скупость', 'слабость', 'слава', 'сладость', 'слеза', 'след',
            'слепень', 'слепок', 'слива', 'слизь', 'слияние', 'слово', 'слог', 'слой', 'слон', 'слуга',
            'слух', 'случай', 'слюда', 'слюна', 'смак', 'смена', 'смерть', 'сметана', 'смех', 'смирение',
            'смог', 'смола', 'смородина', 'сморчок', 'смотр', 'смута', 'смысл', 'смятение', 'снаряд', 'снег',
            'снимок', 'сноп', 'сноровка', 'сноска', 'сносность', 'снотворное', 'собака', 'собор', 'собрание', 'событие',
            'сова', 'совесть', 'совет', 'совок', 'совпадение', 'современник', 'согласие', 'соглядатай', 'содержание', 'содружество',
            'сожаление', 'созвездие', 'созвучие', 'создание', 'сознание', 'созыв', 'сойка', 'сок', 'сокол', 'сокровище',
            'сокровищница', 'солдат', 'солист', 'солнце', 'соловей', 'солод', 'солома', 'соль', 'сомнение', 'сон',
            'соната', 'сонет', 'сообщение', 'соображение', 'соотечественник', 'соотношение', 'сопка', 'соплеменник', 'сопло', 'сопрано',
            'соперник', 'сопка', 'соприкосновение', 'сопровождение', 'сопротивление', 'сор', 'сорняк', 'сорока', 'сорт', 'сосед',
            'соска', 'сосна', 'сосок', 'состав', 'состояние', 'сосуд', 'сосулька', 'сотня', 'сотрудник', 'соус',
            'соха', 'сохранение', 'сочетание', 'сочинение', 'сочувствие', 'союз', 'спазм', 'спальня', 'спасение', 'спектакль',
            'спешка', 'спина', 'спираль', 'список', 'спичка', 'сплав', 'сплетня', 'способ', 'способность', 'спокойствие',
            'спор', 'спорт', 'спорщик', 'справедливость', 'справка', 'спрос', 'спрут', 'спуск', 'спутник', 'сражение',
            'сравнение', 'среда', 'срез', 'срок', 'срочность', 'ссора', 'ссуда', 'ссылка', 'ставка', 'стадион',
            'стадо', 'стаж', 'стакан', 'сталактит', 'сталь', 'стамеска', 'стан', 'станица', 'станок', 'станция',
            'старание', 'старик', 'старина', 'стартер', 'старуха', 'старшина', 'статья', 'статус', 'статуя', 'стая',
            'створ', 'ствол', 'стебель', 'стежок', 'стекло', 'стена', 'стенка', 'степень', 'степь', 'стерлядь',
            'стержень', 'стиль', 'стимул', 'стипендия', 'стирка', 'стих', 'стог', 'стоимость', 'стойка', 'стол',
            'столб', 'столетие', 'столица', 'столп', 'столяр', 'стон', 'стопа', 'стопка', 'сторона', 'сторож',
            'стр', 'страдание', 'страна', 'страница', 'странник', 'странность', 'страсть', 'страус', 'страх', 'стража',
            'стрекоза', 'стрела', 'стрелка', 'стрелок', 'стрельба', 'стремление', 'стремя', 'стриж', 'стрижка', 'стрит',
            'строение', 'строитель', 'строка', 'строй', 'строка', 'струна', 'струя', 'стряпня', 'студент', 'стужа',
            'стук', 'стул', 'ступа', 'ступень', 'ступня', 'стыд', 'стык', 'стычка', 'суббота', 'субъект',
            'суд', 'судак', 'судно', 'судорога', 'судьба', 'судья', 'суета', 'сук', 'сукно', 'султан',
            'сума', 'сумасшествие', 'сумерки', 'сумка', 'сумма', 'суп', 'супруг', 'сурок', 'сустав', 'суть',
            'сутки', 'суфле', 'суша', 'сушка', 'сущность', 'схватка', 'схема', 'сход', 'сходка', 'сходство',
            'сцена', 'счастье', 'счет', 'съезд', 'сыворотка', 'сын', 'сыр', 'сырость', 'сыск', 'сытость',
            'сюжет', 'сюрприз', 'табак', 'табель', 'табло', 'табор', 'табун', 'таблица', 'табурет', 'таволга',
            'таз', 'тайга', 'тайна', 'такса', 'такси', 'такт', 'талант', 'талия', 'талон', 'там',
            'тамбур', 'таможня', 'тампон', 'танго', 'танец', 'танк', 'тапочки', 'тара', 'таракан', 'таран',
            'тарелка', 'тариф', 'тачанка', 'тачка', 'таяние', 'творение', 'творог', 'театр', 'тезис', 'текст',
            'текучесть', 'телега', 'телеграмма', 'теленок', 'телефон', 'тело', 'тельце', 'тема', 'темень', 'темнота',
            'темп', 'температура', 'темя', 'тенденция', 'тенета', 'тень', 'теория', 'тепло', 'тепловоз', 'терем',
            'термин', 'термометр', 'терпение', 'терраса', 'территория', 'террор', 'тесак', 'тесло', 'тесто', 'тесть',
            'тетива', 'тетка', 'тетрадь', 'течение', 'тигр', 'тиран', 'тираж', 'тире', 'тиски', 'титан',
            'титул', 'тиф', 'тишина', 'ткач', 'ткань', 'товар', 'товарищ', 'ток', 'токарь', 'толк',
            'толокно', 'толпа', 'толстяк', 'толща', 'толчок', 'том', 'томление', 'тон', 'тонкость', 'тонна',
            'тополь', 'топор', 'топот', 'топь', 'торг', 'торжество', 'тормоз', 'торопливость', 'торт', 'торф',
            'тоска', 'тост', 'точка', 'точность', 'тощий', 'трава', 'травля', 'трагедия', 'традиция', 'транспорт',
            'трата', 'траур', 'трафарет', 'трах', 'требование', 'тревога', 'трезвость', 'трель', 'трение', 'треск',
            'треснух', 'треть', 'треугольник', 'трещина', 'триумф', 'трибуна', 'трибунал', 'тризна', 'трико', 'триллер',
            'тринадцать', 'трио', 'трогание', 'троица', 'тройка', 'трон', 'тропа', 'тропик', 'тропинка', 'трос',
            'тростник', 'трость', 'тротуар', 'трофей', 'труба', 'трубка', 'труд', 'трудность', 'трудящийся', 'тружени',
            'трюк', 'трюм', 'трюмо', 'тряпка', 'туго', 'туловище', 'туман', 'тумба', 'тундра', 'туннель',
            'тупик', 'тур', 'турист', 'туфля', 'туча', 'тушь', 'тщание', 'тщательность', 'тщета', 'тыква',
            'тысяча', 'тьма', 'тюбик', 'тюк', 'тюлень', 'тюльпан', 'тюль', 'тюрьма', 'тюфяк', 'тявканье',
            'тягость', 'тяжба', 'тяжесть', 'убежище', 'убийство', 'убор', 'убранство', 'убыток', 'уважение', 'увеличение',
            'увертюра', 'уверенность', 'увещевание', 'увлечение', 'увод', 'увольнение', 'угасание', 'углерод', 'угнетение', 'уголок',
            'уголовник', 'уголь', 'угроза', 'угрызение', 'удав', 'удаление', 'удаль', 'удар', 'удача', 'удел',
            'удивление', 'удилище', 'удовольствие', 'удод', 'удой', 'удостоверение', 'удочка', 'ужас', 'ужин', 'узда',
            'узел', 'узкость', 'узник', 'узор', 'уклон', 'уклонение', 'уключина', 'укор', 'украшение', 'укроп',
            'укрощение', 'уксус', 'укус', 'улей', 'улика', 'улитка', 'улица', 'улов', 'улыбка', 'ультиматум',
            'улучшение', 'ум', 'умение', 'умиление', 'умножение', 'умолчание', 'умственность', 'умысел', 'унижение', 'университет',
            'уничтожение', 'упадок', 'упаковка', 'упоминание', 'упор', 'упорство', 'упражнение', 'управа', 'управление', 'упрек',
            'упрочение', 'упрощение', 'упряжь', 'упрямство', 'упускание', 'ураган', 'урал', 'уран', 'уранит', 'уревель',
            'урна', 'уровень', 'урод', 'урожай', 'урок', 'урон', 'усадьба', 'усердие', 'усидчивость', 'усилие',
            'ускорение', 'условие', 'услуга', 'усмешка', 'усмирение', 'усмотрение', 'уста', 'усталость', 'устав', 'установка',
            'уступ', 'уступка', 'устрица', 'устройство', 'устье', 'уступ', 'утварь', 'утверждение', 'утеншение', 'утеха',
            'утес', 'утешение', 'утка', 'утоление', 'утомление', 'уточка', 'утрата', 'утренник', 'утро', 'утюг',
            'уха', 'ухаб', 'ухват', 'ухищрение', 'ухо', 'уход', 'участие', 'участник', 'участок', 'учащийся',
            'учеба', 'учебник', 'ученик', 'ученость', 'ученый', 'учет', 'училище', 'учитель', 'учреждение', 'ушиб',
            'ушко', 'уют', 'фабрика', 'фавор', 'фаза', 'файл', 'факел', 'факт', 'фактор', 'фаланга',
            'фамилия', 'фанера', 'фант', 'фантазия', 'фантик', 'фара', 'фарс', 'фартук', 'фасад', 'фасоль',
            'фауна', 'фаянс', 'февраль', 'федерация', 'фейерверк', 'феликс', 'фельдшер', 'фен', 'ферма', 'фестиваль',
            'фетиш', 'феферол', 'фигура', 'физика', 'фиксатор', 'фикция', 'филин', 'филиал', 'фильм', 'фильтр',
            'философия', 'фимиам', 'финал', 'финик', 'финиш', 'фирма', 'фитиль', 'фишка', 'фланг', 'флаг',
            'флейта', 'флора', 'флот', 'флюгер', 'фойе', 'фокус', 'фольга', 'фонарь', 'фонд', 'фонтан',
            'форель', 'форма', 'формула', 'форпост', 'форт', 'фортуна', 'фосфор', 'фото', 'фотография', 'фраза',
            'фракция', 'франт', 'фрау', 'фрахт', 'фрегат', 'фрейлина', 'френч', 'фреска', 'фронт', 'фрукт',
            'фтор', 'фуга', 'фужер', 'фундамент', 'функция', 'фунт', 'фураж', 'фургон', 'фурор', 'футбол',
            'футляр', 'фуфайка', 'фыркание', 'фюзеляж', 'хаба', 'хаканец', 'халат', 'халва', 'халиф', 'хам',
            'хандра', 'хаос', 'характер', 'хата', 'хвала', 'хвастун', 'хватка', 'хвоиост', 'хвост', 'хвоя',
            'хижина', 'хилость', 'химера', 'химия', 'хирург', 'хитрость', 'хищник', 'хлам', 'хлев', 'хлеб',
            'хлопок', 'хлопоты', 'хлор', 'хлыст', 'хмель', 'хмурость', 'хобот', 'ход', 'ходатайство', 'ходики',
            'ходок', 'хождение', 'хозяин', 'хоккей', 'холм', 'холод', 'холст', 'хомут', 'хор', 'хоромы',
            'хоровод', 'хорошо', 'хорь', 'хоры', 'хохот', 'храбрость', 'храм', 'хранение', 'хребет', 'хрен',
            'хризантема', 'хрип', 'христианин', 'хроника', 'хруст', 'хрусталь', 'хрущ', 'хряк', 'худоба', 'художество',
            'художник', 'хула', 'хулиган', 'хутор', 'цапля', 'царапина', 'царица', 'царство', 'царь', 'цвет',
            'цветник', 'цветок', 'цедра', 'цедулка', 'цезура', 'целебность', 'целина', 'целитель', 'целование', 'целое',
            'целость', 'цель', 'цемент', 'цена', 'цензор', 'цензура', 'ценность', 'центнер', 'центр', 'цепень',
            'цепкость', 'цепочка', 'цепь', 'церемония', 'церковь', 'цех', 'цивилизация', 'цикада', 'цикл', 'циклон',
            'цилиндр', 'цинга', 'циник', 'цинк', 'цирк', 'циркуль', 'цирюльник', 'цистерна', 'цитадель', 'цитата',
            'цифра', 'цоколь', 'цугцванг', 'цыган', 'цыпленок', 'чабан', 'чаевые', 'чайка', 'чайник', 'чайница',
            'час', 'часовня', 'часовой', 'часовщик', 'частица', 'частность', 'часть', 'частушка', 'часы', 'чаша',
            'чашка', 'чаща', 'чаяние', 'чебурек', 'чей', 'чека', 'чекан', 'челн', 'человек', 'челюсть',
            'чемодан', 'чемпион', 'чепец', 'чепуха', 'черви', 'чердак', 'череда', 'черенок', 'череп', 'черепаха',
            'черешня', 'черника', 'чернила', 'чернобурка', 'чернозем', 'чернослив', 'чернота', 'черт', 'чертеж', 'черти',
            'чертовка', 'чертополох', 'чеснок', 'честность', 'честолюбие', 'честь', 'чесунья', 'четверг', 'четверть', 'четки',
            'чех', 'чехол', 'чибис', 'чий', 'чин', 'чинара', 'чиновник', 'число', 'численность', 'чистилище',
            'чистота', 'чистотел', 'читатель', 'чихание', 'член', 'чрево', 'чревоугодие', 'чревоугодник', 'чрезмерность', 'чрезвычайщина',
            'чтение', 'чувак', 'чувство', 'чугун', 'чудак', 'чудо', 'чудотворец', 'чужак', 'чулок', 'чума',
            'чумка', 'чурбан', 'чурка', 'чутье', 'чуть', 'чучело', 'шаблон', 'шаг', 'шайка', 'шакал',
            'шалаш', 'шаль', 'шалость', 'шалун', 'шаман', 'шампанское', 'шампиньон', 'шампунь', 'шанс', 'шантаж',
            'шапка', 'шар', 'шарада', 'шарик', 'шарлатан', 'шарм', 'шарнир', 'шарф', 'шатер', 'шатун',
            'шафран', 'шах', 'шахта', 'шашка', 'шашлык', 'швабра', 'швартов', 'швед', 'швейцар', 'швея',
            'швырок', 'шевеление', 'шедевр', 'шейка', 'шелест', 'шелк', 'шелковица', 'шелуха', 'шельма', 'шепот',
            'шербет', 'шереф', 'шерочка', 'шерсть', 'шерстянка', 'шершень', 'шествие', 'шестерня', 'шесть', 'шеф',
            'шея', 'шило', 'шинель', 'шип', 'шипение', 'шиповник', 'шир', 'ширина', 'ширма', 'шифер',
            'шифр', 'шишка', 'шкаф', 'шкварка', 'шкода', 'школа', 'школьник', 'шкура', 'шлагбаум', 'шлак',
            'шланг', 'шлейф', 'шлем', 'шлепок', 'шлея', 'шлифовка', 'шлюз', 'шлюпка', 'шляпа', 'шмель',
            'шницель', 'шнур', 'шнурок', 'шов', 'шок', 'шоколад', 'шорох', 'шоссе', 'шпага', 'шпагат',
            'шпана', 'шпаргалка', 'шпатель', 'шпиль', 'шпинат', 'шпион', 'шпиц', 'шпора', 'шприц', 'шпроты',
            'шпулька', 'шпунт', 'шрам', 'шрапнель', 'шрифт', 'штаб', 'штабель', 'штакетник', 'штамп', 'штанга',
            'штаны', 'штат', 'штатив', 'штемпель', 'штиль', 'штопор', 'штора', 'шторм', 'штраф', 'штрих',
            'штудирование', 'штука', 'штукатурка', 'штурвал', 'штурм', 'штык', 'штырь', 'шуба', 'шуга', 'шум',
            'шумовка', 'шурин', 'шуруп', 'шут', 'шутка', 'шхуна', 'щавель', 'щебет', 'щебень', 'щегол',
            'щедрость', 'щека', 'щекотка', 'щель', 'щенок', 'щепа', 'щепетильность', 'щепка', 'щепотка', 'щербет',
            'щербина', 'щетина', 'щетка', 'щи', 'щиколотка', 'щипание', 'щипцы', 'щит', 'щука', 'щупальце',
            'щурка', 'эвакуация', 'эволюция', 'эгоизм', 'эдем', 'эй', 'экватор', 'экземпляр', 'экипаж', 'эклер',
            'экономия', 'экран', 'экскаватор', 'экскурсия', 'эксперимент', 'эксперт', 'экспонат', 'экспорт', 'экстаз', 'элегантность',
            'элегия', 'электричество', 'элемент', 'эмаль', 'эмблема', 'эмиграция', 'эмоция', 'эпизод', 'эпилепсия', 'эпилог',
            'эпоха', 'эра', 'эрудиция', 'эскадра', 'эскиз', 'эстафета', 'эстетика', 'эстрада', 'этаж', 'этап',
            'этика', 'этикет', 'этикетка', 'эфир', 'эффект', 'эхо', 'юбилей', 'юбка', 'ювелир', 'юг',
            'юла', 'юмор', 'юнга', 'юнкер', 'юность', 'юноша', 'юнь', 'юрист', 'юрта', 'юстиция',
            'юфть', 'яблоко', 'яблоня', 'явка', 'явление', 'ягненок', 'ягода', 'ягодица', 'ягуар', 'яд',
            'ядро', 'язва', 'язык', 'яичница', 'яйцо', 'якорь', 'якут', 'яма', 'ямщик', 'январь',
            'янтарь', 'ярд', 'ярлык', 'ярмарка', 'ярость', 'яруга', 'ярус', 'ясень', 'ясли', 'ясность',
            'ястреб', 'ятаган', 'яхонт', 'яхта', 'ячейка', 'ячмень', 'яшма', 'ящер', 'ящерица', 'ящик'
        ];

        // ================================================================
        // Создаём Set-версии словарей для быстрого O(1) поиска
        // ================================================================
        const englishWordsSet = new Set(englishWords);
        const russianWordsSet = new Set(russianWords);
        const commonWordsSet = new Set([
            'admin', 'user', 'test', 'hello', 'welcome', 'login', 'pass',
            'password', 'admin', 'root', 'guest', 'master', 'super',
            'moscow', 'russia', 'football', 'computer', 'internet', 'gaming',
            'python', 'student', 'school', 'friend', 'system', 'birth',
            'year', 'date', 'letmein', 'monkey', 'dragon', 'master',
            'test', 'qwerty', 'temp', 'demo'
        ]);
